# This tells PagesCMS where to upload images
media:
  # The folder in your GitHub repo where images will be saved
  input: "static/images/uploads"
  # The public-facing URL path for those images
  # (Matches the 'input' but without 'static/')
  output: "/images/uploads"

# This defines your content types
content:
  # This is one "collection" (e.g., your blog posts)
  - name: "About" # An internal ID
    label: "About Page" # The display name in the admin UI
    type: "page"
    # The folder in your repo where the markdown files live
    path: "content/about" 
    # Optional: Shows these fields in the list view
    view:
      fields: [ "title", "date" ]
  - name: "Documentation"
    label: "docs"
    type: "docs"
      
    # These are the front matter fields for your markdown files
    fields:
      - { name: "title", label: "Title", type: "string" }
      - { name: "draft", label: "Is Draft?", type: "boolean" }
      - { name: "date", label: "Publication Date", type: "date" }
      - { name: "tags", label: "Tags", type: "list" }
      - { name: "body", label: "Content", type: "rich-text" } # This is the main markdown content